// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { env } from "prisma/config";

// Export a plain config object. `defineConfig` provides typings but is optional
// at runtime and can cause editor/compat issues in some setups—using a plain
// object avoids the "module has no exported member 'defineConfig'" problem.
export default {
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "bun prisma/seed.ts",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
};
